name: Notify Merged PR to AI Log Agent

on:
  push:
    branches:
      - m2-pipeline

jobs:
  find-pr-details:
    runs-on: ubuntu-latest
    steps:
      - name: Get merged PR info
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const commitSha = context.sha;

            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              sort: 'updated',
              direction: 'desc',
              per_page: 10
            });

            const mergedPr = prs.data.find(pr =>
              pr.merge_commit_sha === commitSha
            );

            if (!mergedPr) {
              core.setFailed("No merged PR found for this commit.");
              return;
            }

            core.setOutput("url", mergedPr.html_url);
            core.setOutput("number", mergedPr.number);

  invoke-ai-log-agent:
    name: Invoke AI Log Agent
    needs: find-pr-details
    uses: rajithacharith/wso2-organization-templates/.github/workflows/pr-reviewer.yml@main
    with:
      reviewEndpoint: ${{ vars.AI_LOG_AGENT_ANALYZE_ENDPOINT }}
      tokenUrl: ${{ vars.AI_LOG_AGENT_TOKEN_URL }}
      prUrl: ${{ needs.find-pr-details.outputs.url }}
    secrets:
      clientId: ${{ secrets.AI_LOG_AGENT_CLIENT_ID }}
      clientSecret: ${{ secrets.AI_LOG_AGENT_CLIENT_SECRET }}