name: PR Reviewer for Logs

on:
  pull_request_target:
    types: [opened]

jobs:
  call-template:
    uses: rajithacharith/wso2-organization-templates/.github/workflows/pr-reviewer.yml@main
    with:
      prUrl: ${{ github.event.pull_request.html_url }}
    secrets:
      clientId: ${{ secrets.AI_LOG_AGENT_CLIENT_ID }}
      clientSecret: ${{ secrets.AI_LOG_AGENT_CLIENT_SECRET }}
